version: "3.8"

services:
  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./buds-memories_back:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo-data:
